spring.application.name=api-gateway
server.port=8090

#Eureka client
# eureka.instance.hostname=localhost
# eureka.client.register-with-eureka= true
# eureka.client.fetch-registry=true
# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
# eureka.instance.instanceId=${spring.application.name}:${spring.application.instance_id:${random.value}}

#Client microservice
spring.cloud.gateway.routes[0].id=ms-client
spring.cloud.gateway.routes[0].uri=lb://ms-client
spring.cloud.gateway.routes[0].predicates[0]=Path=/v1/clients/**


#Log
logging.level.root=info
logging.level.org.springframework.cloud.gateway=trace
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=info

