services:
  bootcamp-ms-api-gateway:
    image: bootcamp-ms-api-gateway:latest
    container_name: bootcamp-ms-api-gateway
    ports:
      - 8090:8090
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true